#!/bin/sh
set -e

# CPAN modules
if [ -f /cpan.d/cpan.txt ]; then
  if [ -f /cpan.d/debian-packages.txt ] ; then
     if [ ! -f /var/tmp/debian-packages-downloaded ]; then
         apt-get update && \
         apt-get install -y \
                make gcc libperl-dev \
                `cat /cpan.d/debian-packages.txt`

         if [ "$?" -ne "0" ]; then
           exit 1
         fi
         PURGAR=si
         touch /var/tmp/debian-packages-downloaded
     fi
  fi

  for module in `cat /cpan.d/cpan.txt`; do
     echo
     echo "Intentando instalar $module"
     PERL_MM_USE_DEFAULT=1 cpan -i $module
     if [ "$?" -ne "0" ]; then
       exit 1
     fi
  done

  rm -fr /root/.cpan/build /root/.cpan/sources

  if [ "$PURGAR" = si ]; then
      if [ -f /cpan.d/debian-packages.txt ] ; then
         apt-get purge -y --auto-remove make gcc libperl-dev
         rm -rf /var/lib/apt/lists/*
      fi
  fi
fi

if [ "$ONLYPRELOAD" = yes ]; then
   exit
fi

# Apache gets grumpy about PID files pre-existing
rm -f /usr/local/apache2/logs/httpd.pid

exec httpd -DFOREGROUND

